version: '3.9'

services:
  benjinguyen-website-server:
    build:
      dockerfile: ./Dockerfile
    container_name: portfolio_website_server
    ports:
    - "3000:3000"
    volumes:
    - ./public:/public
    restart: always
