version: '3.9'

services:
  benjinguyen-website-server:
    image: benjinguyen-website-server:latest
    container_name: portfolio_website_server
    ports:
    - "3000:3000"
    volumes:
    - ./public:/public
    restart: always
